FROM node:8

=# Create app directory
RUN mkdir -p /usr/src/{{ name }}/

# Install {{ name }} app
ADD {{ name }}/ /usr/src/{{ name }}/
WORKDIR /usr/src/{{ name }}/

# Install node modules
RUN npm install --production
RUN rm /root/.ssh/id_rsa

ENTRYPOINT [ "node", "server.js" ]
