dataRepo:
  path: /Users/sean/code/templatic-data
  name: templatic-data
  url: git+https://github.com/seangallavan/templatic-data.git
engines:
  secrets:
    engine: yaml
    data:
      secret1: secretValue1